### ISSUE TITLE
Connection url for my driver

### ISSUE THREAD

**Issue by Toolenaar** [neo4j-contrib/kubernetes-neo4j#13]
Hi I am having trouble figuring the right url for my driver connection to the cluster. I have setup the cluster on Amazon EKS, and everything seems to be running fine. Now I want to connect my Node.js Express api which runs in another pod on my Kubernetes cluster. However I keep getting the following error:

`getaddrinfo EAI_AGAIN neo4j.default.svc.cluster.local:7687`

I am using the following deployment in which the NEO4J_ENDPOINT = the endpoint used by my Node api app.

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: locali-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: locali-api
    spec:
      nodeSelector:
        instance-type: app
      containers:
      - name: locali-api
        image: 383375125698.dkr.ecr.eu-west-1.amazonaws.com/locali-api:0.0.5
        ports:
        - containerPort: 4000
        env:
        - name: APP_SECRET
          valueFrom:
              secretKeyRef:
                name: app-secret
                key: secret
        - name: NEO4J_PASSWWORD
          valueFrom:
              secretKeyRef:
                name: neo4j-password
                key: password
        - name: NEO4J_USER
          value: neo4j
        - name: NEO4J_ENDPOINT
          value: "bolt://neo4j.default.svc.cluster.local:7687"
---
apiVersion: v1
kind: Service
metadata:
  name: locali-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: locali-api
```

I am quite new to Kubernetes so I am sure I am just missing something basic. But I cant seem to figure out what. Any help is appreciated.
