### ISSUE TITLE
How to setup bolt port through AWS ELB loadbalancer

### ISSUE THREAD

**Issue by Balatriveni** [neo4j-contrib/kubernetes-neo4j#16]
We have a neo4j EC2 instance, we want to add that to Auto scaling group with AWS ELB load balancer.
When  I access the neo4j browser with Load balancer DNS name it works, but bolt connect does nt work.
How to setup AWS Load balancer for neo4j EC2 instance

**Comment by sigginet** [comment]
Apparently, for writes, you need to connect to the leader (if you're using causal cluster) or the RW server (solo setup), so that won't work for autoscaling.
I would setup a read replica setup, this will allow you to autoscale for read purposes.

**Comment by sigginet** [comment]
I just solved this by doing a couple of things:
1. Add a helper deployment that checks which server is a leader and updates a `writeable` label on the core pods
2. Add a NodePort service that shares the port directly to port 30092.

This allowed me to connect to `bolt://HOSTNAMETHATRESOLVESTOCLUSTER:30092/`

I didn't manage to get bolt+routing to work since internal dns names aren't the same as external dns names, so I came up with this solution.

I made a YAML file that sets up everything for you.
There are a couple of caveats:
1. You need to change the namespace to whatever namespace you have.
2. You might need to tweak the password secret name based on your setup
3. Change the nodeport if it's taken on your cluster
4. If the leader changes, it can take up to 30 seconds for this solution to point to the server. You can change the interval in the script to whatever you want.

Here's the YAML that I made:
```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: neo4j-pod-labeling
  namespace: neo4j

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: neo4j-pod-labeling
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "update", "list", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: neo4j-pod-labeling
subjects:
- kind: ServiceAccount
  name: neo4j-pod-labeling
  namespace: neo4j
roleRef:
  kind: Role
  name: neo4j-pod-labeling
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: neo4j-core-auto-labeling
  namespace: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-neo4j-neo4j-core-auto-labeling
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-neo4j-neo4j-core-auto-labeling
    spec:
      containers:
      - env:
        - name: NEO4J_SECRETS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: neo4j-password
              name: neo4j-neo4j-secrets
              optional: false
        image: lachlanevenson/k8s-kubectl:v1.11.2
        imagePullPolicy: IfNotPresent
        name: neo4j-core-auto-labeling
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        command:
          - "sh"
          - "-c"
        args:
          - |
            while true; do
              PODS=$(kubectl get pods -l app=neo4j -l component=core --namespace=neo4j --output=jsonpath={.items..metadata.name})
              AUTH="neo4j:$NEO4J_SECRETS_PASSWORD"
              printf "Leader hunt result: "
              for POD in $PODS; do
                SERVER=$(kubectl get pods $POD --namespace=neo4j --output=jsonpath={.status.podIP})
                LEADER=$(wget -qO- http://$AUTH@$SERVER:7474/db/manage/server/core/writable 2> /dev/null)
                if [[ "$LEADER" == "true" ]]; then
                  printf "$POD"
                else
                  LEADER=false
                fi
                kubectl label pods $POD writeable=$LEADER &> /dev/null
              done
              printf "\n"
              sleep 30
            done
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: neo4j-pod-labeling
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: neo4jbroker
  namespace: neo4j
spec:
  type: NodePort
  ports:
  - port: 7687
    nodePort: 30092
  selector:
    app: neo4j
    component: core
    release: neo4j
    writeable: "true"
```

@mneedham can you integrate this super raw stuff I did into your helm chart template?
